title: Jarrod Parkes
email: parkesfjarrod@gmail.com
description: Learner. Teacher. Developer.
baseurl: ""
url: http://jarrodparkes.github.io
twitter_username: jarrodparkes
github_username:  jarrodparkes

# Build settings
date_format: "%Y-%m-%d"
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
google_analytics: UA-37731779-1