title: Jarrod Parkes
email: parkesfjarrod@gmail.com
description: Learner. Teacher. Developer.
baseurl: ""
url: http://jarrodparkes.github.io
twitter_username: jarrodparkes
github_username:  jarrodparkes

# Build settings
date_format: "%Y-%m-%d"
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
google_analytics: UA-37731779-1

# https://github.com/eduardoboucas/jekyll-social
twitter_format: "@title: @url@tags"
twitter_url_length: 22
twitter_max_length: 140