title: Jarrod Parkes
email: parkesfjarrod@gmail.com
description: Learner. Teacher. Developer.
url: http://jarrodparkes.github.io
github_username:  jarrodparkes

# Build settings
date_format: "%Y-%m-%d"
permalink: pretty
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
google_analytics: UA-37731779-1